// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIRIAUTOPOST.Infrastructure.Data;

#nullable disable

namespace SIRIAUTOPOST.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005160000_MasterPosts")]
    partial class MasterPosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("From")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from");

                    b.Property<string>("To")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("Action", "At")
                        .HasDatabaseName("ix_audit_entries_action_at");

                    b.HasIndex("CustomerId", "At")
                        .HasDatabaseName("ix_audit_entries_customer_id_at");

                    b.ToTable("AUDIT_ENTRIES", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.CollectionMember", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("CollectionId", "PostId")
                        .HasName("pk_collection_members");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_collection_members_post_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_collection_members_workspace_id");

                    b.ToTable("COLLECTION_MEMBERS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.CollectionPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Approval")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("approval");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<List<Guid>>("MediaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("media_ids");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_collection_posts");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("ix_collection_posts_workspace_id_created_at");

                    b.ToTable("COLLECTION_POSTS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AutoPauseReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("auto_pause_reason");

                    b.Property<DateTimeOffset?>("AutoPausedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auto_paused_until");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("browser");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("JobsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("jobs_paused");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_key_hash");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_devices_workspace_id");

                    b.ToTable("DEVICES", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Args")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("args");

                    b.Property<string>("Cmd")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cmd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("DoneAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_at");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_device_commands");

                    b.HasIndex("DeviceId", "Status")
                        .HasDatabaseName("ix_device_commands_device_id_status");

                    b.ToTable("DEVICE_COMMANDS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceEvent", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Seq"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Seq")
                        .HasName("pk_device_events");

                    b.HasIndex("DeviceId", "Seq")
                        .HasDatabaseName("ix_device_events_device_id_seq");

                    b.HasIndex("WorkspaceId", "Seq")
                        .HasDatabaseName("ix_device_events_workspace_id_seq");

                    b.ToTable("DEVICE_EVENTS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<long>("T")
                        .HasColumnType("bigint")
                        .HasColumnName("t");

                    b.HasKey("Id")
                        .HasName("pk_device_logs");

                    b.HasIndex("DeviceId", "T")
                        .HasDatabaseName("ix_device_logs_device_id_t");

                    b.ToTable("DEVICE_LOGS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DevicePairing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_device_pairings");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_device_pairings_code");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_device_pairings_workspace_id");

                    b.ToTable("DEVICE_PAIRINGS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_states");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_states_device_id");

                    b.ToTable("DEVICE_STATES", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ExtensionConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("HasContent")
                        .HasColumnType("boolean")
                        .HasColumnName("has_content");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("settings");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UpdatedByDevice")
                        .HasColumnType("boolean")
                        .HasColumnName("updated_by_device");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_extension_configs");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_extension_configs_device_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_extension_configs_workspace_id");

                    b.ToTable("EXTENSION_CONFIGS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ExtensionImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_extension_images");

                    b.HasIndex("WorkspaceId", "ImageId")
                        .IsUnique()
                        .HasDatabaseName("ix_extension_images_workspace_id_image_id");

                    b.ToTable("EXTENSION_IMAGES", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ImportedPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("link_url");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_key");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_imported_posts");

                    b.HasIndex("WorkspaceId", "PostedAt")
                        .HasDatabaseName("ix_imported_posts_workspace_id_posted_at");

                    b.HasIndex("WorkspaceId", "Source", "SourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_imported_posts_workspace_id_source_source_key");

                    b.ToTable("IMPORTED_POSTS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.LinkSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<Guid>>("AccountIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("account_ids");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PostAsAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_as_account_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_link_sets");

                    b.HasIndex("WorkspaceId", "SortOrder")
                        .HasDatabaseName("ix_link_sets_workspace_id_sort_order");

                    b.ToTable("LINK_SETS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("external_url");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_media_files");

                    b.HasIndex("WorkspaceId", "FolderId")
                        .HasDatabaseName("ix_media_files_workspace_id_folder_id");

                    b.ToTable("MEDIA_FILES", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.MediaFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_media_folders");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_media_folders_workspace_id");

                    b.ToTable("MEDIA_FOLDERS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.PlanSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("key");

                    b.Property<int?>("Accounts")
                        .HasColumnType("integer")
                        .HasColumnName("accounts");

                    b.Property<int?>("Devices")
                        .HasColumnType("integer")
                        .HasColumnName("devices");

                    b.Property<int?>("Posts")
                        .HasColumnType("integer")
                        .HasColumnName("posts");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int?>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.HasKey("Key")
                        .HasName("pk_plan_settings");

                    b.ToTable("PLAN_SETTINGS", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "Free",
                            Accounts = 1,
                            Devices = 1,
                            Posts = 10,
                            Price = 0,
                            Seats = 1
                        },
                        new
                        {
                            Key = "Basic",
                            Accounts = 2,
                            Devices = 1,
                            Posts = 30,
                            Price = 290,
                            Seats = 1
                        },
                        new
                        {
                            Key = "Pro",
                            Accounts = 10,
                            Devices = 3,
                            Price = 790,
                            Seats = 1
                        },
                        new
                        {
                            Key = "Agency",
                            Price = 1990,
                            Seats = 10
                        });
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<Guid?>("ClaimedByDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by_device_id");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<Guid?>("CollectionPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_post_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(7000)
                        .HasColumnType("character varying(7000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ErrorDismissed")
                        .HasColumnType("boolean")
                        .HasColumnName("error_dismissed");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureDetail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_detail");

                    b.Property<bool>("IsTest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_test");

                    b.Property<Guid?>("LinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.PrimitiveCollection<List<Guid>>("MediaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("media_ids");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("SlotKey")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("slot_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target");

                    b.Property<string>("TargetKey")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("target_key");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("target_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasIndex("ClaimedByDeviceId")
                        .HasDatabaseName("ix_posts_claimed_by_device_id");

                    b.HasIndex("LinkId", "ScheduledAt")
                        .HasDatabaseName("ix_posts_link_id_scheduled_at")
                        .HasFilter("link_id IS NOT NULL");

                    b.HasIndex("WorkspaceId", "ScheduledAt")
                        .HasDatabaseName("ix_posts_workspace_id_scheduled_at");

                    b.HasIndex("WorkspaceId", "Status")
                        .HasDatabaseName("ix_posts_workspace_id_status");

                    b.HasIndex("AccountId", "Status", "ScheduledAt")
                        .HasDatabaseName("ix_posts_account_id_status_scheduled_at");

                    b.HasIndex("ScheduleId", "Status", "ScheduledAt")
                        .HasDatabaseName("ix_posts_schedule_id_status_scheduled_at")
                        .HasFilter("schedule_id IS NOT NULL");

                    b.HasIndex("ScheduleId", "TargetKey", "SlotKey")
                        .IsUnique()
                        .HasDatabaseName("ix_posts_schedule_id_target_key_slot_key")
                        .HasFilter("schedule_id IS NOT NULL");

                    b.ToTable("POSTS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.PostCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_post_collections");

                    b.HasIndex("WorkspaceId", "SortOrder")
                        .HasDatabaseName("ix_post_collections_workspace_id_sort_order");

                    b.ToTable("POST_COLLECTIONS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ProcessedPaymentEvent", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type");

                    b.HasKey("Key")
                        .HasName("pk_payment_events");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_payment_events_at");

                    b.ToTable("PAYMENT_EVENTS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Promo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Discount")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("discount");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Uses")
                        .HasColumnType("integer")
                        .HasColumnName("uses");

                    b.HasKey("Id")
                        .HasName("pk_promos");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_promos_code");

                    b.ToTable("PROMOS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ReportShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("period");

                    b.Property<bool>("ShowLogo")
                        .HasColumnType("boolean")
                        .HasColumnName("show_logo");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_json");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)")
                        .HasColumnName("token");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_report_shares");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_report_shares_expires_at");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_report_shares_token");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_report_shares_workspace_id");

                    b.ToTable("REPORT_SHARES", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("AutoDeleteDays")
                        .HasColumnType("integer")
                        .HasColumnName("auto_delete_days");

                    b.Property<int>("BumpHours")
                        .HasColumnType("integer")
                        .HasColumnName("bump_hours");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Cursor")
                        .HasColumnType("integer")
                        .HasColumnName("cursor");

                    b.Property<int>("DripCount")
                        .HasColumnType("integer")
                        .HasColumnName("drip_count");

                    b.Property<string>("DripFrom")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("drip_from");

                    b.Property<string>("DripTo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("drip_to");

                    b.Property<int>("EveryHours")
                        .HasColumnType("integer")
                        .HasColumnName("every_hours");

                    b.Property<string>("FirstTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("first_time");

                    b.Property<DateOnly?>("GeneratedThrough")
                        .HasColumnType("date")
                        .HasColumnName("generated_through");

                    b.Property<Guid>("LinkSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("link_set_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<bool>("NowPending")
                        .HasColumnType("boolean")
                        .HasColumnName("now_pending");

                    b.Property<string>("OnceTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("once_time");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("order");

                    b.Property<string>("Overrides")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("overrides");

                    b.Property<string>("Repeat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("repeat");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<bool>("StartNow")
                        .HasColumnType("boolean")
                        .HasColumnName("start_now");

                    b.PrimitiveCollection<List<string>>("Times")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("times");

                    b.Property<int>("UtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("utc_offset_minutes");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_schedules_collection_id");

                    b.HasIndex("LinkSetId")
                        .HasDatabaseName("ix_schedules_link_set_id");

                    b.HasIndex("WorkspaceId", "Active")
                        .HasDatabaseName("ix_schedules_workspace_id_active");

                    b.ToTable("SCHEDULES", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.SetLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyMax")
                        .HasColumnType("integer")
                        .HasColumnName("daily_max");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("FailStreak")
                        .HasColumnType("integer")
                        .HasColumnName("fail_streak");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("health");

                    b.Property<Guid>("LinkSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("link_set_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("url");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_set_links");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_set_links_workspace_id");

                    b.HasIndex("LinkSetId", "SortOrder")
                        .HasDatabaseName("ix_set_links_link_set_id_sort_order");

                    b.ToTable("SET_LINKS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Snippet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_snippets");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_snippets_workspace_id");

                    b.ToTable("SNIPPETS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.SocialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DefaultTarget")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("default_target");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.PrimitiveCollection<List<string>>("Groups")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("groups");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handle");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("health");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("platform");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_social_accounts");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_social_accounts_device_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_social_accounts_workspace_id");

                    b.ToTable("SOCIAL_ACCOUNTS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cycle");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("plan");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("promo_code");

                    b.Property<string>("ReceiptUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("receipt_url");

                    b.Property<Guid?>("RefundOfId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_of_id");

                    b.Property<string>("StripeInvoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_invoice_id");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<string>("StripeRefundId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_refund_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_transactions_created_at");

                    b.HasIndex("StripeInvoiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_stripe_invoice_id");

                    b.HasIndex("StripePaymentIntentId")
                        .HasDatabaseName("ix_transactions_stripe_payment_intent_id");

                    b.HasIndex("StripeRefundId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_stripe_refund_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_transactions_user_id_created_at");

                    b.ToTable("TRANSACTIONS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cycle");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("password_hash");

                    b.Property<bool>("Paused")
                        .HasColumnType("boolean")
                        .HasColumnName("paused");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("plan");

                    b.Property<DateTimeOffset?>("PlanRenewsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plan_renews_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_stripe_customer_id");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AutoReply")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("auto_reply");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ExtensionOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("extension_online");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notifications")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("notifications");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_workspaces_owner_id");

                    b.ToTable("WORKSPACES", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workspace_members_user_id");

                    b.HasIndex("WorkspaceId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_members_workspace_id_email");

                    b.ToTable("WORKSPACE_MEMBERS", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.CollectionMember", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.PostCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_members_collections_collection_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.CollectionPost", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_members_collection_posts_post_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_members_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.CollectionPost", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_posts_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Device", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceCommand", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_commands_devices_device_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceLog", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_logs_devices_device_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DevicePairing", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_pairings_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceState", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_states_devices_device_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ExtensionConfig", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extension_configs_devices_device_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extension_configs_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ExtensionImage", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extension_images_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ImportedPost", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imported_posts_workspaces_workspace_id");

                    b.OwnsMany("SIRIAUTOPOST.Domain.Entities.ImportedMedia", "Media", b1 =>
                        {
                            b1.Property<Guid>("ImportedPostId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("ContentType")
                                .IsRequired();

                            b1.Property<string>("Key")
                                .IsRequired();

                            b1.Property<long>("Size");

                            b1.Property<string>("SourcePath")
                                .IsRequired();

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("ImportedPostId", "__synthesizedOrdinal")
                                .HasName("pk_imported_posts");

                            b1.ToTable("IMPORTED_POSTS");

                            b1
                                .ToJson("media")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ImportedPostId")
                                .HasConstraintName("fk_imported_posts_imported_posts_imported_post_id");
                        });

                    b.Navigation("Media");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.LinkSet", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_sets_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_files_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.MediaFolder", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_folders_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Post", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.SocialAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_accounts_account_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("ClaimedByDeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_posts_devices_claimed_by_device_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.PostCollection", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_collections_workspaces_workspace_id");

                    b.OwnsOne("SIRIAUTOPOST.Domain.Entities.CollectionSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("PostCollectionId");

                            b1.Property<string>("Footer")
                                .IsRequired();

                            b1.Property<string>("FooterPos")
                                .IsRequired()
                                .HasMaxLength(30);

                            b1.Property<string>("Hashtags")
                                .IsRequired();

                            b1.Property<string>("PageTags")
                                .IsRequired();

                            b1.Property<bool>("RequireApproval");

                            b1.Property<bool>("Shuffle");

                            b1.Property<bool>("Watermark");

                            b1.Property<string>("WatermarkPos")
                                .IsRequired()
                                .HasMaxLength(30);

                            b1.HasKey("PostCollectionId");

                            b1.ToTable("POST_COLLECTIONS");

                            b1
                                .ToJson("settings")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PostCollectionId")
                                .HasConstraintName("fk_post_collections_post_collections_id");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ReportShare", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_shares_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.PostCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_schedules_post_collections_collection_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.LinkSet", null)
                        .WithMany()
                        .HasForeignKey("LinkSetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_schedules_link_sets_link_set_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedules_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.SetLink", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.LinkSet", null)
                        .WithMany()
                        .HasForeignKey("LinkSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_set_links_link_sets_link_set_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_set_links_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Snippet", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_snippets_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.SocialAccount", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_social_accounts_devices_device_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_accounts_workspaces_workspace_id");

                    b.OwnsMany("SIRIAUTOPOST.Domain.Entities.GroupLink", "GroupLinks", b1 =>
                        {
                            b1.Property<Guid>("SocialAccountId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("SocialAccountId", "__synthesizedOrdinal")
                                .HasName("pk_social_accounts");

                            b1.ToTable("SOCIAL_ACCOUNTS");

                            b1
                                .ToJson("group_links")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SocialAccountId")
                                .HasConstraintName("fk_social_accounts_social_accounts_social_account_id");
                        });

                    b.Navigation("GroupLinks");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_users_user_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.User", b =>
                {
                    b.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.LimitOverrides", "Limits", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<int?>("Accounts");

                            b1.Property<int?>("Devices");

                            b1.Property<int?>("Posts");

                            b1.Property<int?>("Seats");

                            b1.HasKey("UserId");

                            b1.ToTable("USERS");

                            b1
                                .ToJson("limit_overrides")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Limits")
                        .IsRequired();
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_users_owner_id");

                    b.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.AntiBanSettings", "AntiBan", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceId");

                            b1.Property<bool>("AutoPause");

                            b1.Property<int>("Max");

                            b1.Property<int>("Min");

                            b1.Property<bool>("Scroll");

                            b1.Property<bool>("Shuffle");

                            b1.Property<bool>("Typing");

                            b1.Property<bool>("Warmup");

                            b1.HasKey("WorkspaceId");

                            b1.ToTable("WORKSPACES");

                            b1
                                .ToJson("anti_ban")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceId")
                                .HasConstraintName("fk_workspaces_workspaces_id");

                            b1.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.AdvancedAntiBanSettings", "Advanced", b2 =>
                                {
                                    b2.Property<Guid>("AntiBanSettingsWorkspaceId");

                                    b2.Property<int>("AutoOffFails");

                                    b2.Property<int>("BlockMax");

                                    b2.Property<int>("BlockMin");

                                    b2.Property<int>("Cooldown");

                                    b2.Property<int>("DailyAll");

                                    b2.Property<int>("FailStreak");

                                    b2.Property<bool>("Focus");

                                    b2.Property<int>("MinGap");

                                    b2.Property<int>("RecentAvoid");

                                    b2.Property<int>("StopFailPct");

                                    b2.HasKey("AntiBanSettingsWorkspaceId")
                                        .HasName("pk_workspaces");

                                    b2.ToTable("WORKSPACES");

                                    b2.WithOwner()
                                        .HasForeignKey("AntiBanSettingsWorkspaceId")
                                        .HasConstraintName("fk_workspaces_workspaces_anti_ban_settings_workspace_id");
                                });

                            b1.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.PlatformLimits", "Limits", b2 =>
                                {
                                    b2.Property<Guid>("AntiBanSettingsWorkspaceId");

                                    b2.Property<int>("Fb");

                                    b2.Property<int>("Ig");

                                    b2.Property<int>("Line");

                                    b2.Property<int>("Th");

                                    b2.Property<int>("Tt");

                                    b2.Property<int>("X");

                                    b2.HasKey("AntiBanSettingsWorkspaceId")
                                        .HasName("pk_workspaces");

                                    b2.ToTable("WORKSPACES");

                                    b2.WithOwner()
                                        .HasForeignKey("AntiBanSettingsWorkspaceId")
                                        .HasConstraintName("fk_workspaces_workspaces_anti_ban_settings_workspace_id");
                                });

                            b1.Navigation("Advanced")
                                .IsRequired();

                            b1.Navigation("Limits")
                                .IsRequired();
                        });

                    b.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.OfflineSettings", "Offline", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceId");

                            b1.Property<bool>("Email");

                            b1.Property<bool>("Line");

                            b1.Property<string>("Policy")
                                .IsRequired()
                                .HasMaxLength(30);

                            b1.Property<bool>("Push");

                            b1.Property<string>("Window")
                                .IsRequired();

                            b1.HasKey("WorkspaceId");

                            b1.ToTable("WORKSPACES");

                            b1
                                .ToJson("offline")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceId")
                                .HasConstraintName("fk_workspaces_workspaces_id");
                        });

                    b.Navigation("AntiBan")
                        .IsRequired();

                    b.Navigation("Offline")
                        .IsRequired();
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_workspace_members_users_user_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");
                });
#pragma warning restore 612, 618
        }
    }
}
