// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIRIAUTOPOST.Infrastructure.Data;

#nullable disable

namespace SIRIAUTOPOST.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003114935_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_media_files");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_media_files_workspace_id");

                    b.ToTable("media_files", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ErrorDismissed")
                        .HasColumnType("boolean")
                        .HasColumnName("error_dismissed");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("failure_code");

                    b.PrimitiveCollection<List<Guid>>("MediaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("media_ids");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_posts_account_id");

                    b.HasIndex("WorkspaceId", "ScheduledAt")
                        .HasDatabaseName("ix_posts_workspace_id_scheduled_at");

                    b.HasIndex("WorkspaceId", "Status")
                        .HasDatabaseName("ix_posts_workspace_id_status");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Snippet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_snippets");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_snippets_workspace_id");

                    b.ToTable("snippets", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.SocialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DefaultTarget")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("default_target");

                    b.PrimitiveCollection<List<string>>("Groups")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("groups");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handle");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("health");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("platform");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_social_accounts");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_social_accounts_workspace_id");

                    b.ToTable("social_accounts", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("plan");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ExtensionOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("extension_online");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_workspaces_owner_id");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_files_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Post", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.SocialAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_accounts_account_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Snippet", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_snippets_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.SocialAccount", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_accounts_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_users_owner_id");

                    b.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.AntiBanSettings", "AntiBan", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceId");

                            b1.Property<bool>("AutoPause");

                            b1.Property<int>("Max");

                            b1.Property<int>("Min");

                            b1.Property<bool>("Scroll");

                            b1.Property<bool>("Shuffle");

                            b1.Property<bool>("Typing");

                            b1.Property<bool>("Warmup");

                            b1.HasKey("WorkspaceId");

                            b1.ToTable("workspaces");

                            b1
                                .ToJson("anti_ban")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceId")
                                .HasConstraintName("fk_workspaces_workspaces_id");

                            b1.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.PlatformLimits", "Limits", b2 =>
                                {
                                    b2.Property<Guid>("AntiBanSettingsWorkspaceId");

                                    b2.Property<int>("Fb");

                                    b2.Property<int>("Ig");

                                    b2.Property<int>("Line");

                                    b2.Property<int>("Th");

                                    b2.Property<int>("Tt");

                                    b2.Property<int>("X");

                                    b2.HasKey("AntiBanSettingsWorkspaceId")
                                        .HasName("pk_workspaces");

                                    b2.ToTable("workspaces");

                                    b2.WithOwner()
                                        .HasForeignKey("AntiBanSettingsWorkspaceId")
                                        .HasConstraintName("fk_workspaces_workspaces_anti_ban_settings_workspace_id");
                                });

                            b1.Navigation("Limits")
                                .IsRequired();
                        });

                    b.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.OfflineSettings", "Offline", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceId");

                            b1.Property<bool>("Email");

                            b1.Property<bool>("Line");

                            b1.Property<string>("Policy")
                                .IsRequired()
                                .HasMaxLength(30);

                            b1.Property<bool>("Push");

                            b1.Property<string>("Window")
                                .IsRequired();

                            b1.HasKey("WorkspaceId");

                            b1.ToTable("workspaces");

                            b1
                                .ToJson("offline")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceId")
                                .HasConstraintName("fk_workspaces_workspaces_id");
                        });

                    b.Navigation("AntiBan")
                        .IsRequired();

                    b.Navigation("Offline")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
