// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIRIAUTOPOST.Infrastructure.Data;

#nullable disable

namespace SIRIAUTOPOST.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003152121_ExtensionSync")]
    partial class ExtensionSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("From")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from");

                    b.Property<string>("To")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("Action", "At")
                        .HasDatabaseName("ix_audit_entries_action_at");

                    b.HasIndex("CustomerId", "At")
                        .HasDatabaseName("ix_audit_entries_customer_id_at");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("browser");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_key_hash");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_devices_workspace_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Args")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("args");

                    b.Property<string>("Cmd")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cmd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("DoneAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_at");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_device_commands");

                    b.HasIndex("DeviceId", "Status")
                        .HasDatabaseName("ix_device_commands_device_id_status");

                    b.ToTable("device_commands", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<long>("T")
                        .HasColumnType("bigint")
                        .HasColumnName("t");

                    b.HasKey("Id")
                        .HasName("pk_device_logs");

                    b.HasIndex("DeviceId", "T")
                        .HasDatabaseName("ix_device_logs_device_id_t");

                    b.ToTable("device_logs", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DevicePairing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_device_pairings");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_device_pairings_code");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_device_pairings_workspace_id");

                    b.ToTable("device_pairings", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_states");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_states_device_id");

                    b.ToTable("device_states", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ExtensionConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("HasContent")
                        .HasColumnType("boolean")
                        .HasColumnName("has_content");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("settings");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UpdatedByDevice")
                        .HasColumnType("boolean")
                        .HasColumnName("updated_by_device");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_extension_configs");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_extension_configs_device_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_extension_configs_workspace_id");

                    b.ToTable("extension_configs", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ExtensionImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_extension_images");

                    b.HasIndex("WorkspaceId", "ImageId")
                        .IsUnique()
                        .HasDatabaseName("ix_extension_images_workspace_id_image_id");

                    b.ToTable("extension_images", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_media_files");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_media_files_workspace_id");

                    b.ToTable("media_files", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.PlanSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("key");

                    b.Property<int?>("Accounts")
                        .HasColumnType("integer")
                        .HasColumnName("accounts");

                    b.Property<int?>("Devices")
                        .HasColumnType("integer")
                        .HasColumnName("devices");

                    b.Property<int?>("Posts")
                        .HasColumnType("integer")
                        .HasColumnName("posts");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<int?>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.HasKey("Key")
                        .HasName("pk_plan_settings");

                    b.ToTable("plan_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "Free",
                            Accounts = 1,
                            Devices = 1,
                            Posts = 10,
                            Price = 0,
                            Seats = 1
                        },
                        new
                        {
                            Key = "Basic",
                            Accounts = 2,
                            Devices = 1,
                            Posts = 30,
                            Price = 290,
                            Seats = 1
                        },
                        new
                        {
                            Key = "Pro",
                            Accounts = 10,
                            Devices = 3,
                            Price = 790,
                            Seats = 1
                        },
                        new
                        {
                            Key = "Agency",
                            Price = 1990,
                            Seats = 10
                        });
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<Guid?>("ClaimedByDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by_device_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ErrorDismissed")
                        .HasColumnType("boolean")
                        .HasColumnName("error_dismissed");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureDetail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_detail");

                    b.PrimitiveCollection<List<Guid>>("MediaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("media_ids");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasIndex("ClaimedByDeviceId")
                        .HasDatabaseName("ix_posts_claimed_by_device_id");

                    b.HasIndex("WorkspaceId", "ScheduledAt")
                        .HasDatabaseName("ix_posts_workspace_id_scheduled_at");

                    b.HasIndex("WorkspaceId", "Status")
                        .HasDatabaseName("ix_posts_workspace_id_status");

                    b.HasIndex("AccountId", "Status", "ScheduledAt")
                        .HasDatabaseName("ix_posts_account_id_status_scheduled_at");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Promo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Discount")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("discount");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Uses")
                        .HasColumnType("integer")
                        .HasColumnName("uses");

                    b.HasKey("Id")
                        .HasName("pk_promos");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_promos_code");

                    b.ToTable("promos", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Snippet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_snippets");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_snippets_workspace_id");

                    b.ToTable("snippets", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.SocialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DefaultTarget")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("default_target");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.PrimitiveCollection<List<string>>("Groups")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("groups");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handle");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("health");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("platform");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_social_accounts");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_social_accounts_device_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_social_accounts_workspace_id");

                    b.ToTable("social_accounts", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cycle");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("plan");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("promo_code");

                    b.Property<Guid?>("RefundOfId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_of_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_transactions_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_transactions_user_id_created_at");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cycle");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("password_hash");

                    b.Property<bool>("Paused")
                        .HasColumnType("boolean")
                        .HasColumnName("paused");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("plan");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ExtensionOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("extension_online");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_workspaces_owner_id");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workspace_members_user_id");

                    b.HasIndex("WorkspaceId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_members_workspace_id_email");

                    b.ToTable("workspace_members", (string)null);
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Device", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceCommand", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_commands_devices_device_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceLog", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_logs_devices_device_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DevicePairing", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_pairings_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.DeviceState", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_states_devices_device_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ExtensionConfig", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extension_configs_devices_device_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extension_configs_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.ExtensionImage", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extension_images_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_files_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Post", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.SocialAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_accounts_account_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("ClaimedByDeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_posts_devices_claimed_by_device_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Snippet", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_snippets_workspaces_workspace_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.SocialAccount", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_social_accounts_devices_device_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_accounts_workspaces_workspace_id");

                    b.OwnsMany("SIRIAUTOPOST.Domain.Entities.GroupLink", "GroupLinks", b1 =>
                        {
                            b1.Property<Guid>("SocialAccountId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("SocialAccountId", "__synthesizedOrdinal")
                                .HasName("pk_social_accounts");

                            b1.ToTable("social_accounts");

                            b1
                                .ToJson("group_links")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SocialAccountId")
                                .HasConstraintName("fk_social_accounts_social_accounts_social_account_id");
                        });

                    b.Navigation("GroupLinks");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_users_user_id");
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.User", b =>
                {
                    b.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.LimitOverrides", "Limits", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<int?>("Accounts");

                            b1.Property<int?>("Devices");

                            b1.Property<int?>("Posts");

                            b1.Property<int?>("Seats");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1
                                .ToJson("limit_overrides")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Limits")
                        .IsRequired();
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_users_owner_id");

                    b.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.AntiBanSettings", "AntiBan", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceId");

                            b1.Property<bool>("AutoPause");

                            b1.Property<int>("Max");

                            b1.Property<int>("Min");

                            b1.Property<bool>("Scroll");

                            b1.Property<bool>("Shuffle");

                            b1.Property<bool>("Typing");

                            b1.Property<bool>("Warmup");

                            b1.HasKey("WorkspaceId");

                            b1.ToTable("workspaces");

                            b1
                                .ToJson("anti_ban")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceId")
                                .HasConstraintName("fk_workspaces_workspaces_id");

                            b1.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.PlatformLimits", "Limits", b2 =>
                                {
                                    b2.Property<Guid>("AntiBanSettingsWorkspaceId");

                                    b2.Property<int>("Fb");

                                    b2.Property<int>("Ig");

                                    b2.Property<int>("Line");

                                    b2.Property<int>("Th");

                                    b2.Property<int>("Tt");

                                    b2.Property<int>("X");

                                    b2.HasKey("AntiBanSettingsWorkspaceId")
                                        .HasName("pk_workspaces");

                                    b2.ToTable("workspaces");

                                    b2.WithOwner()
                                        .HasForeignKey("AntiBanSettingsWorkspaceId")
                                        .HasConstraintName("fk_workspaces_workspaces_anti_ban_settings_workspace_id");
                                });

                            b1.Navigation("Limits")
                                .IsRequired();
                        });

                    b.OwnsOne("SIRIAUTOPOST.Domain.ValueObjects.OfflineSettings", "Offline", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceId");

                            b1.Property<bool>("Email");

                            b1.Property<bool>("Line");

                            b1.Property<string>("Policy")
                                .IsRequired()
                                .HasMaxLength(30);

                            b1.Property<bool>("Push");

                            b1.Property<string>("Window")
                                .IsRequired();

                            b1.HasKey("WorkspaceId");

                            b1.ToTable("workspaces");

                            b1
                                .ToJson("offline")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceId")
                                .HasConstraintName("fk_workspaces_workspaces_id");
                        });

                    b.Navigation("AntiBan")
                        .IsRequired();

                    b.Navigation("Offline")
                        .IsRequired();
                });

            modelBuilder.Entity("SIRIAUTOPOST.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("SIRIAUTOPOST.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_workspace_members_users_user_id");

                    b.HasOne("SIRIAUTOPOST.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");
                });
#pragma warning restore 612, 618
        }
    }
}
